version: '3.9'

services:
    web:
        build: ./app
        ports: 
            - "3000"
    db:
        image: postgres
        restart: always
        volumes:
            - pgdata:/var/lib/postgressql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD

    graphql-engine:
        image: hasura/graphql-engine:v2.0.1.cli-migrations-v3
        ports:
            - "8080:8080"
        depends_on: 
            - db
        restart: always
        volumes:
            - ./hasura/migrations:/hasura-migrations
            - ./hasura/metadata:/hasura-metadata
        environment:
            HASURA_GRAPHQL_DATABASE_URL: $POSTGRES_URL
            HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
           
    adminer:
        image: adminer
        restart: always
        ports:
            - "8090:8080"
volumes:
    pgdata: